Add redis db option
eggjs-community/egg-wechat-api pull request #12
Opened 2018-04-26 13:45 UTC by PowerDos

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

- support redis multi clients option
- modify unittest
- modify readme

2018-04-26 14:36 UTC, thonatos requested changes

2018-04-26 14:36 UTC, thonatos commented on README.md
> +  redisdb: '', // select client of redis
感觉键名用 `redisInstance` 好像更准确一点，你觉得呢？

2018-04-26 14:36 UTC, thonatos commented on config/config.default.js
> +  redisdb: '',
同上。

2018-04-26 14:36 UTC, thonatos commented on lib/wechat-api.js
> +  const { appId, appSecret, redisdb } = app.config.wechatApi || {};
同上。

2018-04-26 14:36 UTC, thonatos commented on lib/wechat-api.js
> +    redis = app.redis.get(redisdb);
同上。

2018-04-26 14:38 UTC, thonatos commented
@PowerDos 

参考一下代码贡献规范：https://eggjs.org/zh-cn/contributing.html

2018-04-26 14:49 UTC, thonatos requested changes

2018-04-26 14:49 UTC, thonatos commented on .travis.yml
> -- redis-server
`travis` 里 redis 单实例和集群，下面两种方式应该都可以解决。

- https://github.com/tedious/Stash/blob/master/tests/travis/redis_setup.sh
- https://docs.travis-ci.com/user/docker/

2018-04-27 03:17 UTC, duncup submitted a review, later dismissed
不要带 package-lock.json 文件

2018-04-27 15:13 UTC, thonatos requested changes

2018-04-27 15:13 UTC, thonatos commented on test/fixtures/apps/wechat-api-test-redis-multi-clients/config/config.unittest.js
> +  redisInstance: process.env.REDIS_INSTANCE,
上面已经指定了 instance，这边就不需要用环境变量了

2018-04-27 15:13 UTC, thonatos commented on .travis.yml
> -  # WECHAT_API_APP_ID
这里删掉是获取不到环境变量的

2018-04-28 01:19 UTC, duncup reviewed
我没什么别的建议了。 剩下都看 @thonatos 的吧。

2018-05-07 16:35 UTC, thonatos approved these changes

2018-05-07 16:37 UTC, merged